# Generated by Django 3.0.5 on 2020-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_lessons_number'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mylessons',
            field=models.ManyToManyField(related_name='myusers', to='search.lessons'),
        ),
    ]
