# Generated by Django 3.0.5 on 2020-05-27 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_mylessons'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='institute',
            field=models.CharField(choices=[('船院', '船舶海洋与建筑工程学院'), ('电院', '电子信息与电气工程学院'), ('机动', '机械与动力工程学院'), ('材料', '材料科学与工程学院'), ('环境', '环境科学与工程学院'), ('生医工', '生物医学工程学院'), ('航空', '航空航天学院'), ('数学', '数学科学学院'), ('物理', '物理与天文学院'), ('化学', '化学化工学院'), ('致远', '致远学院'), ('海洋', '海洋学院'), ('生命科学', '生命科学技术学院'), ('农学院', '农业与生物学院'), ('药学院', '药学院'), ('医学院', '医学院'), ('安泰', '安泰经济与管理学院'), ('法学院', '凯原法学院'), ('外院', '外国语学院'), ('人文', '人文学院'), ('马院', '马克思主义学院'), ('媒体', '媒体与传播学院'), ('设计', '设计学院')], default='电院', max_length=20),
        ),
    ]
