# Generated by Django 3.0.5 on 2020-04-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discuss', '0003_remove_question_replies'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
