# Generated by Django 3.0.5 on 2020-05-15 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='number',
            field=models.CharField(default='aaa', max_length=10),
        ),
    ]
