# Generated by Django 3.0.5 on 2020-05-06 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessons',
            name='weeks',
            field=models.CharField(default='1-16周', max_length=20),
            preserve_default=False,
        ),
    ]
