# Generated by Django 3.0.5 on 2020-05-10 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='owner',
        ),
    ]
