# Generated by Django 3.0.5 on 2020-05-16 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20200515_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='time',
        ),
        migrations.RemoveField(
            model_name='lessons',
            name='weeks',
        ),
        migrations.AddField(
            model_name='lessons',
            name='day',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons',
            name='is_interval',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons',
            name='time_ended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons',
            name='time_started',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons',
            name='week_ended',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lessons',
            name='week_started',
            field=models.IntegerField(default=0),
        ),
    ]
