# Generated by Django 3.0.5 on 2020-05-30 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20200516_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='semester',
            field=models.CharField(default='2019-2020-2', max_length=15),
        ),
    ]
