# Generated by Django 3.0.5 on 2020-05-30 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20200530_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='location',
            field=models.CharField(default='上院102', max_length=10),
        ),
    ]
