# Generated by Django 3.0.5 on 2020-05-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0007_auto_20200530_1931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='institute',
            field=models.CharField(default='电子信息与电气工程学院', max_length=20),
        ),
    ]
